#ifndef PARAMS_H
#define PARAMS_H

#include <vulkan/vulkan.h>

#define PREFERRED_DEVICE_TYPE VK_PHYSICAL_DEVICE_TYPE_DISCRETE_GPU
#define FALLBACK_DEVICE_TYPE  VK_PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU

#define TARGET_DISPLAY_WIDTH  1920
#define TARGET_DISPLAY_HEIGHT 1200
#define TARGET_REFRESH_RATE   165000
#define TARGET_GLOBAL_ALPHA   1.0f

#define TARGET_SURFACE_FORMAT VK_FORMAT_A8B8G8R8_UNORM_PACK32
#define TARGET_COLOR_SPACE    VK_COLOR_SPACE_SRGB_NONLINEAR_KHR
#define TARGET_PRESENT_MODE   VK_PRESENT_MODE_FIFO_KHR

#endif